import React, { useState } from 'react';
import { apiService } from '../services/api';

const defaultJob = 'Software engineer role requiring strong Java, Python, React, SQL, Docker, and collaborative delivery experience.';
export default function InterviewStudio({ profile }) {
  const [jobDescription, setJobDescription] = useState(defaultJob);
  const [questions, setQuestions] = useState([]); const [index, setIndex] = useState(0);
  const [transcript, setTranscript] = useState(''); const [audio, setAudio] = useState(null);
  const [result, setResult] = useState(null); const [ats, setAts] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const resumeText = `${profile.first_name} ${profile.last_name}. Skills: ${profile.skills.join(', ')}. ${profile.experience.map(x => `${x.title} at ${x.company}: ${x.responsibilities.join(' ')}`).join(' ')}`;
  const generate = async () => { setLoading(true); setError(''); try { const data = await apiService.generateInterviewQuestions(profile, jobDescription); setQuestions(data.questions); setIndex(0); setResult(null); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  const runAts = async () => { setLoading(true); setError(''); try { setAts(await apiService.scoreAts(resumeText, jobDescription)); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  const transcribe = async () => { if (!audio) return; setLoading(true); setError(''); try { const data = await apiService.transcribeRecording(audio); setTranscript(data.transcript); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  const evaluate = async () => { const question = questions[index]; if (!question || !transcript.trim()) return; setLoading(true); setError(''); try { setResult(await apiService.evaluateInterviewAnswer(question.question, transcript, question.grounding)); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  const current = questions[index];
  return <div className="max-w-4xl mx-auto space-y-6">
    <div><h2 className="text-2xl font-extrabold">AI Interview Studio</h2><p className="text-xs text-slate-400">Recorded audio and reviewed transcripts only — no live copilot or WebRTC.</p></div>
    {error && <div className="p-3 rounded-lg bg-red-500/10 border border-red-500/30 text-red-300 text-sm">{error}</div>}
    <section className="bg-slate-900/60 border border-slate-800 rounded-2xl p-6 space-y-4"><label className="text-xs font-bold uppercase text-slate-400">Target job description</label><textarea value={jobDescription} onChange={e => setJobDescription(e.target.value)} rows="4" className="w-full bg-slate-950 border border-slate-800 rounded-lg p-3 text-sm" /><div className="flex gap-3"><button onClick={generate} disabled={loading} className="px-4 py-2 bg-indigo-600 rounded-lg text-sm font-bold disabled:opacity-50">{loading ? 'Working…' : 'Generate interview questions'}</button><button onClick={runAts} disabled={loading} className="px-4 py-2 border border-slate-700 rounded-lg text-sm">ATS compatibility score</button></div></section>
    {ats && <section className="bg-slate-900/60 border border-slate-800 rounded-2xl p-6"><div className="text-3xl font-black text-indigo-400">{ats.score}/100</div><p className="text-xs text-slate-400 mt-1">ATS parseability: {ats.parseability}</p><ul className="mt-3 text-sm text-slate-300 list-disc pl-5">{[...ats.strengths, ...ats.issues].map(item => <li key={item}>{item}</li>)}</ul></section>}
    {current && <section className="bg-slate-900/60 border border-slate-800 rounded-2xl p-6 space-y-4"><p className="text-xs uppercase text-indigo-300 font-bold">Question {index + 1} of {questions.length} · {current.type}</p><h3 className="font-bold text-lg">{current.question}</h3><input type="file" accept="audio/wav,audio/mpeg,audio/mp4,audio/webm,audio/ogg" onChange={e => setAudio(e.target.files?.[0])} className="text-xs" /><button onClick={transcribe} disabled={!audio || loading} className="ml-3 text-xs underline disabled:opacity-50">Upload recorded audio & transcribe</button><textarea value={transcript} onChange={e => setTranscript(e.target.value)} placeholder="Paste or review the interview transcript…" rows="6" className="w-full bg-slate-950 border border-slate-800 rounded-lg p-3 text-sm" /><div className="flex gap-3"><button onClick={evaluate} disabled={loading || !transcript.trim()} className="px-4 py-2 bg-indigo-600 rounded-lg text-sm font-bold disabled:opacity-50">Evaluate answer</button>{index < questions.length - 1 && <button onClick={() => { setIndex(index + 1); setTranscript(''); setResult(null); }} className="text-sm">Next question →</button>}</div>{result && <div className="p-4 bg-slate-950 rounded-lg"><div className="text-xl font-bold text-indigo-300">{result.score}/100</div><ul className="text-sm text-slate-300 list-disc pl-5">{result.feedback.map(item => <li key={item}>{item}</li>)}</ul></div>}</section>}
    {!current && !loading && <div className="text-center p-10 border border-dashed border-slate-800 rounded-2xl text-sm text-slate-500">Generate a question set to start a practice interview.</div>}
  </div>;
}
